#ifndef SPARSE_VECTOR_HPP
#define SPARSE_VECTOR_HPP

#include "Matrix.hpp"
#include "Vector.hpp"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <iterator>
#include <vector>

template <class T> class SparseVector {
private:
  // Add your data members here!
  unsigned int mDimension;
  std::vector<unsigned int> mIndices;
  std::vector<T> mValues;

public:
  // creates an empty vector of dimensionality 0.
  SparseVector() { mDimension = 0; }
  // Creates a vector of dimensionality dim. It starts with 0 nonzero elements
  // which need to be set using setValue
  SparseVector(unsigned int dim) {
    mDimension = dim;
    // apparently vector initializes by itself
  }

  // assignment operators and copy constructor should be automatically
  // generated by the compiler when using a std::vector for internal storing.
  // However, test that assignment works!

  // sets the value v_i of the vector. if it does not exist it is added
  void setValue(unsigned int index, T value) {
    auto it = std::lower_bound(mIndices.begin(), mIndices.end(), index);
    // checks the distance from the start to the index that should be inserted
    size_t pos = std::distance(mIndices.begin(), it);

	if (value != T(0))
	{
		if (it != mIndices.end() && *it == index)
		{
			mValues[pos] = value;
		}
		else 
		{
			mIndices.insert(it, index);
			mValues.insert(mValues.begin() + pos, value);
		}
	}
	else // value == T(0)
	{
		if (it != mIndices.end() && *it == index)
		{
			mIndices.erase(it);
			mValues.erase(mValues.begin()+pos);
		}
	}
	




  }

  // returns the value v_i of the vector. Returns 0 if the value is not stored
  T getValue(unsigned int index) const {
    // again we find the index (it) which is not smaller than index (index)
    auto it = std::lower_bound(mIndices.begin(), mIndices.end(), index);

    // we then store the position from the start
    size_t pos = std::distance(mIndices.begin(), it);

    if (it != mIndices.end() && *it == index) // if the index is
    {
      return mValues[pos];
    } else {
      return T(0);
    }
  }

  // returns the dimensionality of the vector
  unsigned int size() const { return mDimension; }

  // returns the number stored elements
  unsigned int nonZeroes() const { return mValues.size(); }
  // returns the index of the ith stored nonzero entry (in increasing order)
  unsigned int indexNonZero(unsigned int i) const {
    // mindices pos
    assert(i < nonZeroes());
    return mIndices[i];
  }
  // returns the value of the ith stored nonzero entry (in increasing order)
  T valueNonZero(unsigned int i) const {
    assert(i < nonZeroes());
    return mValues[i];
  }

  // adds x too the current vector
  SparseVector<T> &operator+=(SparseVector<T> const &x) {
    assert(mDimension == x.size());
    std::vector<unsigned int> newIndices;
    std::vector<T> newValues;
    unsigned int i = 0, j = 0;
    while (i < nonZeroes() && j < x.nonZeroes()) {
        unsigned int idx1 = indexNonZero(i);
        unsigned int idx2 = x.indexNonZero(j);
        if (idx1 < idx2) {
            newIndices.push_back(idx1);
            newValues.push_back(valueNonZero(i));
            i++;
        } else if (idx2 < idx1) {
            newIndices.push_back(idx2);
            newValues.push_back(x.valueNonZero(j));
            j++;
        } else { // idx1 == idx2
            T sum = valueNonZero(i) + x.valueNonZero(j);
            if (sum != T(0)) {
                newIndices.push_back(idx1);
                newValues.push_back(sum);
            }
            i++;
            j++;
        }
    }
    while (i < nonZeroes()) {
        newIndices.push_back(indexNonZero(i));
        newValues.push_back(valueNonZero(i));
        i++;
    }
    while (j < x.nonZeroes()) {
        newIndices.push_back(x.indexNonZero(j));
        newValues.push_back(x.valueNonZero(j));
        j++;
    }
    mIndices = newIndices;
    mValues = newValues;
    return *this;
  }
  // subtracts x from the current vector
  SparseVector<T> &operator-=(SparseVector<T> const &x) 
  {
	assert(mDimension == x.size());
    std::vector<unsigned int> newIndices;
    std::vector<T> newValues;
    unsigned int i = 0, j = 0;
    while (i < nonZeroes() && j < x.nonZeroes()) {
        unsigned int idx1 = indexNonZero(i);
        unsigned int idx2 = x.indexNonZero(j);
        if (idx1 < idx2) {
            newIndices.push_back(idx1);
            newValues.push_back(valueNonZero(i));
            i++;
        } else if (idx2 < idx1) {
            newIndices.push_back(idx2);
            newValues.push_back(-x.valueNonZero(j));
            j++;
        } else { // idx1 == idx2
            T diff = valueNonZero(i) - x.valueNonZero(j);
            if (diff != T(0)) {
                newIndices.push_back(idx1);
                newValues.push_back(diff);
            }
            i++;
            j++;
        }
    }
    while (i < nonZeroes()) {
        newIndices.push_back(indexNonZero(i));
        newValues.push_back(valueNonZero(i));
        i++;
    }
    while (j < x.nonZeroes()) {
        newIndices.push_back(x.indexNonZero(j));
        newValues.push_back(-x.valueNonZero(j));
        j++;
    }
    mIndices = newIndices;
    mValues = newValues;
	return *this;
  }
};

// computes z= x+y, equivalent to z=x, z+=y
template <class T>
SparseVector<T> operator+(SparseVector<T> const &x, SparseVector<T> const &y)
{
	SparseVector<T> result = x;
	result += y;
	return result;
}

// computes z= x-y, equivalent to z=x, z-=y
template <class T>
SparseVector<T> operator-(SparseVector<T> const &x, SparseVector<T> const &y)
{
	SparseVector<T> result = x;
	result -= y;
	return result;
}

// computes the matrix-vector product of a dense matrix and sparse vector z=Ax.
// The result is a dense vector.
template <class T>
Vector<T> operator*(Matrix<T> const &A, SparseVector<T> const &x)
{
	assert(A.GetNumberOfColumns() == x.size());
	Vector<T> z(A.GetNumberOfRows());

	for (unsigned int j = 0; j < x.nonZeroes(); j++)
	{
		unsigned int J = x.indexNonZero(j);
		T val = x.valueNonZero(j);
		for (int i = 0; i < A.GetNumberOfRows(); i++)
		{
			z[i] += A(i, J) * val;
		}
	}
	return z;
}

// computes the matrix-vector product of a dense matrix and sparse vector
// z=x^TA. The result is a dense vector.
template <class T>
Vector<T> operator*(SparseVector<T> const &x, Matrix<T> const &A)
{
	assert(x.size() == A.GetNumberOfRows());
	int n_cols = A.GetNumberOfColumns();
	Vector<T> z(n_cols);

	for (unsigned int k = 0; k < x.nonZeroes(); k++)
	{
		unsigned int I = x.indexNonZero(k);
		T value = x.valueNonZero(k);
		for (int j = 0; j < n_cols; j++)
		{
			z[j] += value * A(I, j);
		}
	}
	return z;
}

#endif
