#ifndef SPARSE_VECTOR_HPP
#define SPARSE_VECTOR_HPP

#include "Vector.hpp"
#include "Matrix.hpp"
#include <algorithm>
#include <cstddef>
#include <iterator>
#include <vector>

template<class T> class SparseVector{
private:
	//Add your data members here!
	unsigned int mDimension;
	std::vector<unsigned int> mIndices;
	std::vector<T> mValues;

public:
	//creates an empty vector of dimensionality 0.
	SparseVector()
	{
		mDimension = 0;
	}
	// Creates a vector of dimensionality dim. It starts with 0 nonzero elements
	// which need to be set using setValue
	SparseVector(unsigned int dim)
	{
		mDimension = dim;
		// apparently vector initializes by itself
	}

	// assignment operators and copy constructor should be automatically
	// generated by the compiler when using a std::vector for internal storing.
	// However, test that assignment works!

	//sets the value v_i of the vector. if it does not exist it is added
	void setValue(unsigned int index, T value)
	{
		auto it = std::lower_bound(mIndices.begin(), mIndices.end(), index);
		// checks the distance from the start to the index that should be inserted
		size_t pos = std::distance(mIndices.begin(), it); 

		// then we check if we should insert
		// we do this if the index is in the indices
		// recall that it should we < end unless its larget than all
		if (it != mIndices.end() && *it == index) // already exists
		{
			mValues[pos] = value;
		} 
		else  // does not exist and we insert
		{
			mIndices.insert(it, index);
			mValues.insert(mValues.begin() + pos, value);
		}
	}

	//returns the value v_i of the vector. Returns 0 if the value is not stored
	T getValue(unsigned int index) const
	{
		// again we find the index (it) which is not smaller than index (index)
		auto it = std::lower_bound(mIndices.begin(), mIndices.end(), index);

		// we then store the position from the start 
		size_t pos = std::distance(mIndices.begin(), it); 

		if (it != mIndices.end() && *it == index) // if the index is 
		{
			return mValues[pos];
		} 
		else 
		{
			return T(0);

		}
	}

	//returns the dimensionality of the vector
	unsigned int size() const;

	// returns the number stored elements
	unsigned int nonZeroes() const;
	//returns the index of the ith stored nonzero entry (in increasing order)
	unsigned int indexNonZero(unsigned int i) const;
	//returns the value of the ith stored nonzero entry (in increasing order)
	T valueNonZero(unsigned int i) const;

	//adds x too the current vector
	SparseVector<T>& operator+= (SparseVector<T> const& x);
	//subtracts x from the current vector
	SparseVector<T>& operator-= (SparseVector<T> const& x);
};


// computes z= x+y, equivalent to z=x, z+=y
template<class T>
SparseVector<T> operator+(SparseVector<T> const& x, SparseVector<T> const& y);

// computes z= x-y, equivalent to z=x, z-=y
template<class T>
SparseVector<T> operator-(SparseVector<T> const& x, SparseVector<T> const& y);


// computes the matrix-vector product of a dense matrix and sparse vector z=Ax.
// The result is a dense vector.
template<class T>
Vector<T> operator* (Matrix<T> const& A, SparseVector<T> const& x);

// computes the matrix-vector product of a dense matrix and sparse vector z=x^TA.
// The result is a dense vector.
template<class T>
Vector<T> operator* (SparseVector<T> const& x, Matrix<T> const& A);


#endif
